// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6RN_3a_p9zegyAaTByYOGWh7XvYBsdWo',
    appId: '1:875957972199:web:63be769401f4399c9e0642',
    messagingSenderId: '875957972199',
    projectId: 'healthfirst-d2404',
    authDomain: 'healthfirst-d2404.firebaseapp.com',
    storageBucket: 'healthfirst-d2404.firebasestorage.app',
    measurementId: 'G-LQNJDF74YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOfA7DTwmMC56U-fVUbTU0zm1KVCoDGDo',
    appId: '1:875957972199:android:f9acddf31034916e9e0642',
    messagingSenderId: '875957972199',
    projectId: 'healthfirst-d2404',
    storageBucket: 'healthfirst-d2404.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpG63R4xPIqX1t--KujCYyp37qXc5jiCs',
    appId: '1:875957972199:ios:06705a501487679e9e0642',
    messagingSenderId: '875957972199',
    projectId: 'healthfirst-d2404',
    storageBucket: 'healthfirst-d2404.firebasestorage.app',
    iosBundleId: 'com.example.heathfirstMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpG63R4xPIqX1t--KujCYyp37qXc5jiCs',
    appId: '1:875957972199:ios:06705a501487679e9e0642',
    messagingSenderId: '875957972199',
    projectId: 'healthfirst-d2404',
    storageBucket: 'healthfirst-d2404.firebasestorage.app',
    iosBundleId: 'com.example.heathfirstMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6RN_3a_p9zegyAaTByYOGWh7XvYBsdWo',
    appId: '1:875957972199:web:338a2d83797c2a9a9e0642',
    messagingSenderId: '875957972199',
    projectId: 'healthfirst-d2404',
    authDomain: 'healthfirst-d2404.firebaseapp.com',
    storageBucket: 'healthfirst-d2404.firebasestorage.app',
    measurementId: 'G-GR01YPP0LW',
  );
}
